
hello_test:
    path:     test/{slug}
    defaults: { _controller: ALPlatformeBundle:Deal:hello }

display_deal:
    path:     display/{id}
    defaults: { _controller: ALPlatformeBundle:Deal:display }

add_deal:
    path:     add_deal
    defaults: { _controller: ALPlatformeBundle:Deal:add }

deal_success:
    path:     deal_success{id}
    defaults: { _controller: ALPlatformeBundle:Deal:success }

add_backlink:
    path:     add-backlink
    defaults: { _controller: ALPlatformeBundle:Deal:backlink }
