<?php

namespace AL\PlatformeBundle\Repository;

/**
 * BacklinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacklinkRepository extends \Doctrine\ORM\EntityRepository
{
}
